export const siteConfig = {
  name: "Artillery Cleaning Services",
  shortName: "Artillery",
  url: "https://artillery-theta.vercel.app",
  phoneDisplay: "610-329-0240",
  phoneHref: "tel:+16103290240",
  faxDisplay: "610-872-2005",
  email: "artillerycleaningservices@gmail.com",
  emailHref: "mailto:artillerycleaningservices@gmail.com",
  addressLine1: "413 Franklin Street",
  addressLine2: "Chester, PA 19013",
  baseLocation: "Chester, PA",
  serviceArea: "Delaware County & Chester, PA",
  serviceAreaList: ["Delaware County, PA", "Chester, PA"],
  hoursDisplay: "Monday - Saturday | 8:00 AM - 6:00 PM",
  hours: {
    opens: "08:00",
    closes: "18:00",
    days: [
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
    ],
  },
  coreServices: [
    "Commercial office cleaning",
    "School and facility cleaning",
    "Industrial cleaning",
    "Post-construction cleanup",
  ],
} as const;
